services:

  frontend:
    build:
      context: /home/$USER/hiveconnect-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    networks:
      - app-network
    restart: unless-stopped

  autoprov:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - frontend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
