services:

  frontend:
    build:
      context: /home/$USER/hiveconnect_fe
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Change port as necessary
    networks:
      - app-network

  autoprov:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: 192.168.90.72
      DB_PORT: 5432
      DB_NAME: hiveDB
      DB_USERNAME: apollo
      DB_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - frontend

networks:
  app-network:
    driver: bridge
