# Log file name and location
logging.file.name=/app/logs/application.log
logging.file.max-size=10MB
logging.level.root=DEBUG


# Commented Out Configurations

# ACS Database
# acs.datasource.url=jdbc:postgresql://10.160.0.65:5433/acsDB
acs.datasource.url=${ACS_DATASOURCE_URL}
acs.datasource.username=${ACS_DATASOURCE_USERNAME}
# acs.datasource.password=ap0ll0ap0ll0!
acs.datasource.password=${ACS_DATASOURCE_PASSWORD}
acs.datasource.driver-class-name=${ACS_DATASOURCE_DRIVER_CLASS_NAME}
acs.jpa.hibernate.ddl-auto=${ACS_JPA_HIBERNATE_DDL_AUTO}

# Hive Database
#hiveDB.datasource.url=jdbc:postgresql://192.168.90.72:5432/hiveDB
#hiveDB.datasource.username=postgres
#hiveDB.datasource.password=hive_dev
#hiveDB.datasource.driver-class-name=org.postgresql.Driver
#hiveDB.jpa.hibernate.ddl-auto=update

# Subscriber Database
#clientdb.datasource.url=jdbc:postgresql://192.168.90.72:5432/subscriberDB
#clientdb.datasource.username=postgres
#clientdb.datasource.password=hive_dev
#clientdb.datasource.driver-class-name=org.hibernate.dialect.PostgreSQLDialect
#clientdb.jpa.hibernate.ddl-auto=update

# IPAM Database
#ipamDB.datasource.url=jdbc:postgresql://192.168.90.72:5432/ipamDB
#ipamDB.datasource.username=postgres
#ipamDB.datasource.password=hive_dev
#ipamDB.datasource.driver-class-name=org.postgresql.Driver
#ipamDB.jpa.hibernate.ddl-auto=update

# OLT Database
#oltDB.datasource.url=jdbc:postgresql://192.168.90.72:5432/oltDB
#oltDB.datasource.username=postgres
#oltDB.datasource.password=hive_dev
#oltDB.datasource.driver-class-name=org.postgresql.Driver
#oltDB.jpa.hibernate.ddl-auto=update

# Logging Configuration
logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG

# Thread Pool Configuration
CoreThreads=${CORE_THREADS}
MaxCoreThreads=${MAX_CORE_THREADS}

#------------------------------------------------------------------------------------#

# Active DataSource Configuration

# ACS Database
#acs.datasource.url=jdbc:mysql://172.91.0.136:3306/acsDB
#acs.datasource.username=dev_user
#acs.datasource.password=remote_passwordletmein
#acs.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#acs.jpa.hibernate.ddl-auto=update
#acs.jpa.show-sql=true

# IPAM Database (Old MySQL Configuration)
#  ipamDB.datasource.url=jdbc:mysql://10.160.0.85:3307/ipamDB
 ipamDB.datasource.url=${IPAMDB_DATASOURCE_URL}
 ipamDB.datasource.username=${IPAMDB_DATASOURCE_USERNAME}
 ipamDB.datasource.password=${IPAMDB_DATASOURCE_PASSWORD}
 ipamDB.datasource.driver-class-name=${IPAMDB_DATASOURCE_DRIVER_CLASS_NAME}
 ipamDB.jpa.show-sql=${IPAMDB_JPA_SHOW_SQL}
 ipamDB.jpa.hibernate.ddl-auto=${IPAMDB_JPA_HIBERNATE_DDL_AUTO}
 ipamDB.jpa.properties.hibernate.dialect=${IPAMDB_JPA_PROPERTIES_HIBERNATE_DIALECT}

# Hive Database (Old MySQL Configuration)
#  hiveDB.datasource.url=jdbc:mysql://10.160.0.85:3307/hiveDB
 hiveDB.datasource.url=${HIVEDB_DATASOURCE_URL}
 hiveDB.datasource.username=${HIVEDB_DATASOURCE_USERNAME}
 hiveDB.datasource.password=${HIVEDB_DATASOURCE_PASSWORD}
 hiveDB.datasource.driver-class-name=${HIVEDB_DATASOURCE_DRIVER_CLASS_NAME}
 hiveDB.jpa.show-sql=${HIVEDB_JPA_SHOW_SQL}
 hiveDB.jpa.hibernate.ddl-auto=${HIVEDB_JPA_HIBERNATE_DDL_AUTO}
 hiveDB.jpa.properties.hibernate.dialect=${HIVEDB_JPA_PROPERTIES_HIBERNATE_DIALECT}

# Subscriber Database (Old MySQL Configuration)
#  clientdb.datasource.url=jdbc:mysql://10.160.0.85:3307/subscriberDB
 clientdb.datasource.url=${CLIENTDB_DATASOURCE_URL}
 clientdb.datasource.username=${CLIENTDB_DATASOURCE_USERNAME}
 clientdb.datasource.password=${CLIENTDB_DATASOURCE_PASSWORD}
 clientdb.datasource.driver-class-name=${CLIENTDB_DATASOURCE_DRIVER_CLASS_NAME}
 clientdb.jpa.show-sql=${CLIENTDB_JPA_SHOW_SQL}
 clientdb.jpa.hibernate.ddl-auto=${CLIENTDB_JPA_HIBERNATE_DDL_AUTO}
 clientdb.jpa.properties.hibernate.dialect=${CLIENTDB_JPA_PROPERTIES_HIBERNATE_DIALECT}

# Olt Database (Old MySQL Configuration)
#  oltDB.datasource.url=jdbc:mysql://10.160.0.85:3307/oltDB
 oltDB.datasource.url=${OLTDB_DATASOURCE_URL}
 oltDB.datasource.username=${OLTDB_DATASOURCE_USERNAME}
 oltDB.datasource.password=${OLTDB_DATASOURCE_PASSWORD}
 oltDB.datasource.driver-class-name=${OLTDB_DATASOURCE_DRIVER_CLASS_NAME}
 oltDB.jpa.show-sql=${OLTDB_JPA_SHOW_SQL}
 oltDB.jpa.hibernate.ddl-auto=${OLTDB_JPA_HIBERNATE_DDL_AUTO}
 oltDB.jpa.properties.hibernate.dialect=${OLTDB_JPA_PROPERTIES_HIBERNATE_DIALECT}

bezkoder.app.jwtSecret= ${JWT_SECRET}
bezkoder.app.jwtExpirationMs=${JWT_EXPIRATION_MS}

#-----------------------------------------------------------------------------------#
# urls

acsApiUrl=${ACS_API_URL}
playbookMonitoringApiUrl=${PLAYBOOK_MONITORING_API_URL}
playbookPreProvUrl=${PLAYBOOK_PREPROV_URL}
playbookGetJobUrl=${PLAYBOOK_GET_JOB_URL}
ansibleAccessToken=${ANSIBLE_ACCESS_TOKEN}
prometheusApiUrl=${PROMETHEUS_API_URL}
app.jwkSetUri=${JWK_URI}


#-----------------------------------------------------------------------------------#

# INET Database (Old MySQL Configuration)
# inet.jpa.hibernate.ddl-auto=update
# inet.datasource.url=jdbc:mysql://vhostclient.dctechmicro.com:3306/c4_infosystem
# inet.datasource.username=c4_trashcan
# inet.datasource.password=cantrash123
# inet.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ACS Database (Alternative Old MySQL Configuration)
# acs.datasource.url=jdbc:mysql://172.91.0.136:3306/acsDB
# acs.datasource.username=hiveConnect
# acs.datasource.password=2020@p0LL0!
# acs.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Packages Database (Old MySQL Configuration)
# packageDB.datasource.url=jdbc:mysql://localhost:3306/packagesDB
# packageDB.datasource.username=root
# packageDB.datasource.password=root
# packageDB.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# packageDB.jpa.hibernate.ddl-auto=update
# packageDB.jpa.show-sql=true

# Server SSL Configuration
# server.port=8002
# server.ssl.key-store=/home/ubuntu/IP-Management-Test/keystore.jks
# server.ssl.key-store-password=password
# server.ssl.keyStoreType=JKS
# server.ssl.keyAlias=keystore

# Legacy Database Credentials
# db_name=clients_for_activation
# username=root
# password=root
# localhost:3306


