# Log file name and location
# logging.file.name=/app/logs/application.log
# logging.file.max-size=10MB
# logging.level.root=DEBUG
# logging.level.apiLogger=INFO
# logging.level.apiErrorLogger=ERROR
# logging.config=./src/main/resources/logback-spring.xml


# Commented Out Configurations

# ACS Database
acs.datasource.url=jdbc:mysql://192.168.32.23:3308/acsDB
acs.datasource.username=apollo
acs.datasource.password=ap0ll0ap0ll0!
acs.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
acs.jpa.show-sql=true
acs.jpa.hibernate.ddl-auto=update
acs.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Logging Configuration
# logging.level.org.springframework=DEBUG
# logging.level.org.hibernate=DEBUG

# Thread Pool Configuration
CoreThreads=4
MaxCoreThreads=10

#------------------------------------------------------------------------------------#

# Active DataSource Configuration

# IPAM Database (Old MySQL Configuration)
 ipamDB.datasource.url=jdbc:mysql://192.168.32.23:3308/ipamDB
 ipamDB.datasource.username=apollo
 ipamDB.datasource.password=ap0ll0ap0ll0!
 ipamDB.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 ipamDB.jpa.show-sql=true
 ipamDB.jpa.hibernate.ddl-auto=update
 ipamDB.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

 hiveDB.datasource.url=jdbc:mysql://192.168.32.23:3308/hiveDB
 hiveDB.datasource.username=apollo
 hiveDB.datasource.password=ap0ll0ap0ll0!
 hiveDB.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 hiveDB.jpa.show-sql=true
 hiveDB.jpa.hibernate.ddl-auto=update
 hiveDB.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

 clientdb.datasource.url=jdbc:mysql://192.168.32.23:3308/subscriberDB
 clientdb.datasource.username=apollo
 clientdb.datasource.password=ap0ll0ap0ll0!
 clientdb.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 clientdb.jpa.show-sql=true
 clientdb.jpa.hibernate.ddl-auto=update
 clientdb.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

 oltDB.datasource.url=jdbc:mysql://192.168.32.23:3308/oltDB
 oltDB.datasource.username=apollo
 oltDB.datasource.password=ap0ll0ap0ll0!
 oltDB.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 oltDB.jpa.show-sql=true
 oltDB.jpa.hibernate.ddl-auto=update
 oltDB.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

bezkoder.app.jwtSecret= 5b3c89bbe407c7c8897a8d1255dbf4559f8f87f758f4ad6b12a2656e7cc743c
# bezkoder.app.jwtExpirationMs=${JWT_EXPIRATION_MS}

#-----------------------------------------------------------------------------------#
# urls
absApiUrl=https://md-dev.payconnect.io/abs-status-callback/
acsApiUrl=https://acs-cdo-backend.k8s.apolloglobal.net/
playbookBandwidthLimitationApiUrl=https://awx.apolloglobal.net/api/v2/job_templates/106/
playbookMonitoringApiUrl=https://awx.apolloglobal.net/api/v2/job_templates/104/
playbookPreProvUrl=https://awx.apolloglobal.net/api/v2/job_templates/105/
playbookGetJobUrl=https://awx.apolloglobal.net/api/v2/jobs/
playbookMigrationUrl=https://awx.apolloglobal.net/api/v2/job_templates/107/
ansibleAccessToken=rWu4F93c8q28swkpDN7iKzEYWKwJkW
ansibleMigrationToken=rWu4F93c8q28swkpDN7iKzEYWKwJkW
absApiKey=3bfd4454759283d7643f0d30daa0c92d5baab12e1b994c09795e2fe42366b0e1
prometheusApiUrl=https://dctech-prometheus.apolloglobal.net:9090/api/v1/query
app.jwkSetUri=https://wcdssi.apolloglobal.net:8443/auth/realms/workconnect-test/protocol/openid-connect/certs



#-----------------------------------------------------------------------------------#
