# Log file name and location
logging.file.name=/app/logs/application.log
logging.file.max-size=10MB
logging.level.root=DEBUG


# Commented Out Configurations

# ACS Database
acs.datasource.url=${ACS_DATASOURCE_URL}
acs.datasource.username=${ACS_DATASOURCE_USERNAME}
acs.datasource.password=${ACS_DATASOURCE_PASSWORD}
acs.datasource.driver-class-name=${ACS_DATASOURCE_DRIVER_CLASS_NAME}
acs.jpa.hibernate.ddl-auto=${ACS_JPA_HIBERNATE_DDL_AUTO}
acs.jpa.show-sql=${ACS_JPA_SHOW_SQL}


# Logging Configuration
logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG

# Thread Pool Configuration
CoreThreads=${CORE_THREADS}
MaxCoreThreads=${MAX_CORE_THREADS}

#------------------------------------------------------------------------------------#

# Active DataSource Configuration

# IPAM Database (Old MySQL Configuration)
 ipamDB.datasource.url=${IPAMDB_DATASOURCE_URL}
 ipamDB.datasource.username=${IPAMDB_DATASOURCE_USERNAME}
 ipamDB.datasource.password=${IPAMDB_DATASOURCE_PASSWORD}
 ipamDB.datasource.driver-class-name=${IPAMDB_DATASOURCE_DRIVER_CLASS_NAME}
 ipamDB.jpa.hibernate.ddl-auto=${IPAMDB_JPA_HIBERNATE_DDL_AUTO}
 ipamDB.jpa.show-sql=${IPAMDB_JPA_SHOW_SQL}
#  ipamDB.jpa.properties.hibernate.dialect=${IPAMDB_JPA_PROPERTIES_HIBERNATE_DIALECT}

 hiveDB.datasource.url=${HIVEDB_DATASOURCE_URL}
 hiveDB.datasource.username=${HIVEDB_DATASOURCE_USERNAME}
 hiveDB.datasource.password=${HIVEDB_DATASOURCE_PASSWORD}
 hiveDB.datasource.driver-class-name=${HIVEDB_DATASOURCE_DRIVER_CLASS_NAME}
 hiveDB.jpa.show-sql=${HIVEDB_JPA_SHOW_SQL}
 hiveDB.jpa.hibernate.ddl-auto=${HIVEDB_JPA_HIBERNATE_DDL_AUTO}
 hiveDB.jpa.properties.hibernate.dialect=${HIVEDB_JPA_PROPERTIES_HIBERNATE_DIALECT}

 clientdb.jpa.hibernate.ddl-auto=${CLIENTDB_JPA_HIBERNATE_DDL_AUTO}
 clientdb.datasource.url=${CLIENTDB_DATASOURCE_URL}
 clientdb.datasource.username=${CLIENTDB_DATASOURCE_USERNAME}
 clientdb.datasource.password=${CLIENTDB_DATASOURCE_PASSWORD}
 clientdb.datasource.driver-class-name=${CLIENTDB_DATASOURCE_DRIVER_CLASS_NAME}
 clientdb.jpa.show-sql=${CLIENTDB_JPA_SHOW_SQL}
 clientdb.jpa.properties.hibernate.dialect=${CLIENTDB_JPA_PROPERTIES_HIBERNATE_DIALECT}

 oltDB.datasource.url=${OLTDB_DATASOURCE_URL}
 oltDB.datasource.username=${OLTDB_DATASOURCE_USERNAME}
 oltDB.datasource.password=${OLTDB_DATASOURCE_PASSWORD}
 oltDB.datasource.driver-class-name=${OLTDB_DATASOURCE_DRIVER_CLASS_NAME}
 oltDB.jpa.show-sql=${OLTDB_JPA_SHOW_SQL}
 oltDB.jpa.hibernate.ddl-auto=${OLTDB_JPA_HIBERNATE_DDL_AUTO}
 oltDB.jpa.properties.hibernate.dialect=${OLTDB_JPA_PROPERTIES_HIBERNATE_DIALECT}

# bezkoder.app.jwtSecret= ${JWT_SECRET}
# bezkoder.app.jwtExpirationMs=${JWT_EXPIRATION_MS}

#-----------------------------------------------------------------------------------#
# urls

acsApiUrl=${ACS_API_URL}
playbookMonitoringApiUrl=${PLAYBOOK_MONITORING_API_URL}
playbookPreProvUrl=${PLAYBOOK_PREPROV_URL}
playbookGetJobUrl=${PLAYBOOK_GET_JOB_URL}
ansibleAccessToken=${ANSIBLE_ACCESS_TOKEN}
prometheusApiUrl=${PROMETHEUS_API_URL}
# app.jwkSetUri=${JWK_URI}


#-----------------------------------------------------------------------------------#
